del *.log*1 /s
del *.log*2 /s
del *.log*3 /s
del *.log*4 /s
del *.log*5 /s
del *.log*6 /s
del *.log*7 /s
del *.log*8 /s
del *.log*9 /s
del *.log*10 /s
del *.log*11 /s
del *.log*12 /s
del *.log*13 /s
del *.log*14 /s
del *.log*15 /s

del *.art*1 /s
del *.art*2 /s
del *.art*3 /s
del *.art*4 /s
del *.art*5 /s
del *.art*6 /s
del *.art*7 /s
del *.art*8 /s
del *.art*9 /s
del *.art*10 /s
del *.art*11 /s
del *.art*12 /s
del *.art*13 /s
del *.art*14 /s
del *.art*15 /s

del *.txt*1 /s
del *.txt*2 /s
del *.txt*3 /s
del *.txt*4 /s
del *.txt*5 /s
del *.txt*6 /s
del *.txt*7 /s
del *.txt*8 /s
del *.txt*9 /s
del *.txt*10 /s
del *.txt*11 /s
del *.txt*12 /s
del *.txt*13 /s
del *.txt*14 /s
del *.txt*15 /s

del *.rpt*1 /s
del *.rpt*2 /s
del *.rpt*3 /s
del *.rpt*4 /s
del *.rpt*5 /s
del *.rpt*6 /s
del *.rpt*7 /s
del *.rpt*8 /s
del *.rpt*9 /s
del *.rpt*10 /s
del *.rpt*11 /s
del *.rpt*12 /s
del *.rpt*13 /s
del *.rpt*14 /s
del *.rpt*15 /s
del *.jrl*1 /s

del *dat*1 /s
del *dat*2 /s
del *dat*3 /s

exit